On transparency.
larseggert/draft-ietf-modpod-group-processes pull request #74
Opened 2024-12-30 08:51 UTC by elear

Incorporates mailing list proposal.

Closes #69.

2025-01-08 11:17 UTC, larseggert commented on draft-ecahc-moderation.md
> +decided by the IESG.
Is it the IESG, or is it the IETF Chair? My original doc homed it with the Chair, since that's where the current "special-case" moderation is homed. We can change it to the IESG, but it will require other changes in the doc.

2025-01-08 17:55 UTC, elear commented on draft-ecahc-moderation.md
> +decided by the IESG.
I'm good with the IETF chair.  Will change accordingly.

2025-01-08 18:13 UTC, sayrer commented
Mmm, I think it has to say

> All actions taken by the moderation team SHALL be reported to the person being moderated and the IETF Chair.

2025-01-08 18:39 UTC, elear commented
The text that is there says:
> SHALL be reported to the forum in which the person was banned, as well as to that person

I may have made that a bit too compact.

2025-01-08 18:41 UTC, sayrer commented
I caught that part, but it's only after 14 days.

2025-01-08 18:50 UTC, sayrer commented
I think we can say this closes #79 with that edit, but there still might be something to say about what WG Chairs have to inform participants of. I think getting a first draft out would be better than going after that point, though.

2025-01-08 19:35 UTC, becarpenter commented on draft-ecahc-moderation.md
> +decided by the IESG.
Not disagreeing, but maybe we need to be clear whether this is confidential, and if so whether the IETF Chair can expose it to the whole IESG.

2025-01-09 06:40 UTC, larseggert requested changes

2025-01-09 06:40 UTC, larseggert commented on draft-ecahc-moderation.md
> +moderation, and refer interested parties to that forum.  All actions
Let's not make the chair create that, let's require the moderation team to create (and moderate, hah) that forum.

(Pet peeve of mine is the org piling more things on the IETF chair, see my chair-may-delegate draft.)

2025-01-09 06:40 UTC, larseggert commented on draft-ecahc-moderation.md
> +community in a manner decided by the IESG.
That 14-day text is much too prescriptive. Let's instead require that the moderation team must define gradual reporting of actions.

2025-01-09 09:52 UTC, elear commented on draft-ecahc-moderation.md
> +moderation, and refer interested parties to that forum.  All actions
That's not appropriate in this instance.  The community is directed to that forum by this document, and only the IESG should be telling the community where to go.  I realize that this is "chair dumping" but in this case, it's a very rare event.

2025-01-09 09:52 UTC, elear commented on draft-ecahc-moderation.md
> +community in a manner decided by the IESG.
I disagree.  This is a matter of accountability **of** the moderator team **to** the community, and they cannot specify their own terms in that regard.

2025-01-09 17:30 UTC, sayrer commented on draft-ecahc-moderation.md
> +community in a manner decided by the IESG.
I agree with Eliot here. I think the day count is not too important. We can always try 14 days and adjust it in the inevitable update (it is difficult to imagine getting everything right the first time).

The reason my document gives the moderation team a lot of power is so that they don't have to use it most of the time.

2025-01-09 19:28 UTC, becarpenter commented on draft-ecahc-moderation.md
> +community in a manner decided by the IESG.
Rather than hard-coding 14 days, we probably need $REPORTING-INTERVAL so that it can be changed without a new RFC... But I agree with Eliot about accountability.

2025-01-10 05:58 UTC, larseggert commented on draft-ecahc-moderation.md
> +community in a manner decided by the IESG.
I also agree about accountability. But I think it is enough to say that the mod team MUST adhere to reasonable and proportional reporting, rather than detailing the "how" of it.

2025-01-10 06:18 UTC, sayrer commented on draft-ecahc-moderation.md
> +community in a manner decided by the IESG.
Going to have to give you an 🙄 eyeroll emoji on this one, sorry. 14 days is a long time, and doesn't really constrain the moderator team. We do have a pick a number to set the boundary.

6 seconds? 6 minutes? 6 days? All too short.

6 weeks? That is a really long time.

2025-01-10 06:36 UTC, larseggert commented on draft-ecahc-moderation.md
> +community in a manner decided by the IESG.
My concern is the subject of a moderation action doing an appeal if it's been 15 days.

2025-01-10 07:19 UTC, elear commented on draft-ecahc-moderation.md
> +community in a manner decided by the IESG.
@larseggert 

First, this isn't particularly about appeal.  Rather, it's about transparency.  14 days and everyone needs to know what happened.

But even if it were about appeals, we say that people should have the right to appeal moderator decisions.  So what's the problem?

2025-01-10 07:20 UTC, elear commented
Lars, please approve this PR.

2025-01-20 06:56 UTC, larseggert commented on draft-ecahc-moderation.md
> +moderation, and refer interested parties to that forum.  All actions
OK. Please rebase and then let's put this on the IESG, too.

2025-01-20 06:57 UTC, larseggert commented on draft-ecahc-moderation.md
> +community in a manner decided by the IESG.
OK, if everyone wants to be prescriptive, I'm in the rough.

2025-01-20 06:58 UTC, larseggert approved these changes
@elear please rebase and let's make the IESG own the discussion forum.

2025-01-20 08:09 UTC, elear commented
@larseggert I'm suffering a moment of git incompetence.  Please bare with me.

2025-01-20 11:45 UTC, larseggert commented
@elear Almost there. Could you undo the change to `.github/CODEOWNERS` that adds an extra newline?

2025-01-20 12:07 UTC, elear commented
@larseggert Ok.  Pls review.

2025-01-20 12:08 UTC, larseggert approved these changes

2025-01-20 12:08 UTC, merged